name: Build&Clean (Linux) (feature)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+_feature_*

jobs:
  Build-n-Clean_Linux_feature:

    name: Build&Clean Job (Linux) (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Установка пакетов и модулей
      run: |
        pip3 install numpy
        pip3 install matplotlib
        sudo aptitude install texlive-fonts-recommended texlive-fonts-extra
        sudo apt-get install dvipng
    - name: Запуск скрипта для проверки сборки
      run: bash .github/scripts/Build\&Clean\ \(Linux\,\ проверка\ сборки\ и\ очистки\).sh