name: Build&Clean (Linux) (feature)

on:
  push:
    branches:
      - feature

jobs:
  Build-n-Clean_Linux:

    name: Build&Clean Job (Linux) (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки сборки
      run: bash .github/scripts/Build\&Clean\ \(Linux\,\ проверка\ сборки\ и\ очистки\).sh
