name: Build&Clean (Linux)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  Build-n-Clean_Linux_master:

    name: Build&Clean Job (Linux) (master)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки сборки
      run: bash .github/scripts/Build\&Clean\ \(Linux\,\ проверка\ сборки\ и\ очистки\).sh
