name: Build&Clean (macOS)

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  Build-n-Clean_macOS:

    name: Build&Clean Job (macOS) (master)
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2

    - name: Установка MacPorts
      run: bash .github/scripts/Build\&Clean\ \(macOS\,\ установка\ MacPorts\).sh

    - name: Установка gmake
      run: bash .github/scripts/Build\&Clean\ \(macOS\,\ установка\ gmake\).sh
  
    - name: Запуск скрипта для проверки сборки
      run: bash .github/scripts/Build\&Clean\ \(macOS\,\ проверка\ сборки\ и\ очистки\).sh
