name: NoDebugging (feature)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+_feature_*

jobs:
  NoDebugging_feature:

    name: NoDebugging Job (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки флага отладки
      run: bash .github/scripts/NoDebugging.sh
