name: NoObjects (feature)

on:
  push:
    branches:
      - feature

jobs:
  NoObjects:

    name: NoObjects Job (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Запуск скрипта для проверки директории объектных файлов
      run: bash .github/scripts/NoObjects.sh
