name: VersionCheck (feature)

on:
  push:
    branches:
      - feature

jobs:
  VersionCheck_feature:

    name: VersionCheck (feature)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Получение истории коммитов
      run: git fetch --prune --unshallow origin +refs/heads/*:refs/remotes/origin/*
    - name: Вызов скрипта для проверки версии
      run: bash .github/scripts/VersionCheck_feature.sh